### ISSUE TITLE
ZIP file in repository contains broken app

### ISSUE THREAD

**Issue by plaetzchen** [satrik/wledQuickControl#1]
Downloading the ZIP from the repository leads to an .app that can't be run by macOS. Maybe do "official" releases in GitHub?

**Comment by satrik** [comment]
You're right, the app wasn't working. I think the problem was just that the last build of the app was ~11 month ago. In between were a lot of macOS updates. 
I've re-build the app and uploaded it, should work now. Would be nice if you can test it :)

**Comment by plaetzchen** [comment]
Yeah, I built myself already and that works great. But the file still doesn't work for me. Did you export it with a developer profile for distribution?

**Comment by satrik** [comment]
The problem seems to be gatekeeper - Apple doesn't allow side loaded Apps anymore. Only possibility is to explicitly remove the quarantine tag from the .app.
I've added a small shell script which does the this now. Poorly, but it must be executed manually 🤷🏼‍♂️
